# Generated by Django 4.2.5 on 2023-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='cuisine',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
