# Generated by Django 4.2.5 on 2023-12-31 17:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieHub', '0002_alter_amenity_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='building',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326),
        ),
    ]
