# Generated by Django 4.2.5 on 2023-12-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieHub', '0003_alter_amenity_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
